#
# rGuiLayout initialization configuration options
#
# NOTE: This file is loaded at application startup,
# if file is not found, default values are applied
#
SHOW_WINDOW_INFO                       1                                # Show control panel
SHOW_CONTROL_TOOLTIPS                  1                                # Show controls tooltips on mouse hover
INIT_WINDOW_MAXIMIZED                  0                                # Initialize window maximized
SHOW_IMAGE_GRID                        1                                # Show image grid
GRID_LINES_SPACING                     8                                # Grid lines spacing
GUI_VISUAL_STYLE                       0                                # UI visual style selected
